documento = {
    "titulo": "Documento #" + str(i),
    "texto": random.choice([
        "El sol brilla en el cielo.",
        "Los pájaros cantan en el parque.",
        "La vida es hermosa.",
        "Aprender programación es divertido.",
        "Me encanta la comida italiana.",
        "Caminar en la playa es relajante.",
        "Los libros son una fuente de conocimiento.",
        "La amistad es un tesoro invaluable.",
        "La música puede cambiar tu estado de ánimo.",
        "Disfruta cada momento de la vida.",
        "El café por la mañana es imprescindible.",
        "Viajar amplía tu horizonte.",
        "La familia es lo más importante.",
        "La naturaleza es asombrosa.",
        "Nunca dejes de aprender.",
        "Sonríe, es gratis.",
        "La paciencia es una virtud.",
        "La perseverancia lleva al éxito.",
        "La honestidad siempre es la mejor opción.",
        "Haz lo que amas y no trabajarás un día en tu vida.",
        "La belleza está en los ojos del espectador.",
        "La creatividad no tiene límites.",
        "La vida es un regalo preciado.",
        "Sé agradecido por lo que tienes.",
        "El tiempo vuela, disfruta el momento.",
        "El deporte es bueno para la salud.",
        "La música es el lenguaje del alma.",
        "Si puedes soñarlo, puedes lograrlo.",
        "Ama y sé amado.",
        "La risa es la mejor medicina.",
        "La educación es la clave del éxito.",
        "El respeto es fundamental en todas las relaciones.",
        "La humildad es una virtud admirable.",
        "Siembra buenas acciones y cosecharás buenos resultados.",
        "La vida es un viaje, no un destino.",
        "La simplicidad es la última sofisticación.",
        "La curiosidad conduce al conocimiento.",
        "El cambio es la única constante en la vida.",
        "La imaginación es el principio de la creación.",
        "La diversidad nos enriquece.",
        "La verdad siempre prevalece.",
        "La naturaleza es nuestro hogar.",
        "La felicidad viene de dentro.",
        "La empatía es fundamental para entender a los demás.",
        "La libertad es un derecho humano fundamental.",
        "Aprende de tus errores y sigue adelante.",
        "El amor todo lo puede.",
        "La perseverancia es la madre del éxito.",
        "El conocimiento es poder.",
        "La tecnología está cambiando el mundo.",
        "El trabajo en equipo es esencial.",
        "Cada día es una nueva oportunidad.",
        "La pasión te impulsa a alcanzar tus metas.",
        "La gratitud transforma la vida.",
        "La amabilidad es contagiosa.",
        "El arte es una forma de expresión.",
        "La justicia es un pilar de la sociedad.",
        "La salud es riqueza.",
        "La honestidad es la mejor política.",
        "El amor es lo que realmente importa.",
        "La perseverancia supera el talento.",
        "El cambio es una oportunidad para crecer.",
        "La música alimenta el alma.",
        "La educación es un camino hacia el éxito.",
        "El silencio a veces es la mejor respuesta.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con el tiempo.",
        "La libertad es un derecho sagrado.",
        "El éxito es un viaje, no un destino.",
        "El aprendizaje es un proceso continuo.",
        "El respeto es la base de todas las relaciones.",
        "La amistad verdadera perdura.",
        "La valentía supera el miedo.",
        "La gratitud cambia la perspectiva.",
        "El amor trae alegría a la vida.",
        "La risa alivia el estrés.",
        "La belleza está en todas partes.",
        "La curiosidad despierta la mente.",
        "La pasión impulsa la creatividad.",
        "La paciencia es una fuente de fortaleza.",
        "La creatividad no tiene límites.",
        "La comprensión genera armonía.",
        "La sinceridad construye relaciones sólidas.",
        "La amistad es un lazo indestructible.",
        "La generosidad es una virtud admirable.",
        "La honestidad es un acto de valentía.",
        "El amor es un regalo preciado.",
        "La sonrisa es un gesto poderoso.",
        "La educación es el camino hacia el progreso.",
        "La compasión alivia el sufrimiento.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con acciones.",
        "La lealtad es un tesoro.",
        "La ética guía nuestras decisiones.",
        "La libertad es un derecho fundamental.",
        "La confianza es la base de toda relación.",
        "La lealtad es una promesa sincera.",
        "La ética guía nuestras acciones.",
        "La libertad es un derecho sagrado.",
        "La perseverancia conduce al éxito.",
        "La generosidad abre puertas.",
        "El respeto mutuo es esencial.",
        "La gratitud nos llena de alegría.",
        "La amistad es un tesoro inestimable.",
        "La comprensión construye puentes.",
        "La tolerancia fomenta la convivencia.",
        "La confianza es fundamental en todas las relaciones.",
        "La humildad es una virtud valiosa.",
        "Siembra buenas acciones y cosecharás buenos resultados.",
        "La vida es un viaje, no un destino.",
        "La simplicidad es la última sofisticación.",
        "La curiosidad conduce al conocimiento.",
        "El cambio es la única constante en la vida.",
        "La imaginación es el principio de la creación.",
        "La diversidad nos enriquece.",
        "La verdad siempre prevalece.",
        "La naturaleza es nuestro hogar.",
        "La felicidad viene de dentro.",
        "La empatía es fundamental para entender a los demás.",
        "La libertad es un derecho humano fundamental.",
        "Aprende de tus errores y sigue adelante.",
        "El amor todo lo puede.",
        "La perseverancia es la madre del éxito.",
        "El conocimiento es poder.",
        "La tecnología está cambiando el mundo.",
        "El trabajo en equipo es esencial.",
        "Cada día es una nueva oportunidad.",
        "La pasión te impulsa a alcanzar tus metas.",
        "La gratitud transforma la vida.",
        "La amabilidad es contagiosa.",
        "El arte es una forma de expresión.",
        "La justicia es un pilar de la sociedad.",
        "La salud es riqueza.",
        "La honestidad es la mejor política.",
        "El amor es lo que realmente importa.",
        "La perseverancia supera el talento.",
        "El cambio es una oportunidad para crecer.",
        "La música alimenta el alma.",
        "La educación es un camino hacia el éxito.",
        "El silencio a veces es la mejor respuesta.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con el tiempo.",
        "La libertad es un derecho sagrado.",
        "El éxito es un viaje, no un destino.",
        "El aprendizaje es un proceso continuo.",
        "El respeto es la base de todas las relaciones.",
        "La amistad verdadera perdura.",
        "La valentía supera el miedo.",
        "La gratitud cambia la perspectiva.",
        "El amor trae alegría a la vida.",
        "La risa alivia el estrés.",
        "La belleza está en todas partes.",
        "La curiosidad despierta la mente.",
        "La pasión impulsa la creatividad.",
        "La paciencia es una fuente de fortaleza.",
        "La creatividad no tiene límites.",
        "La comprensión genera armonía.",
        "La sinceridad construye relaciones sólidas.",
        "La amistad es un lazo indestructible.",
        "La generosidad es una virtud admirable.",
        "La honestidad es un acto de valentía.",
        "El amor es un regalo preciado.",
        "La sonrisa es un gesto poderoso.",
        "La educación es el camino hacia el progreso.",
        "La compasión alivia el sufrimiento.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con acciones.",
        "La lealtad es un tesoro.",
        "La ética guía nuestras decisiones.",
        "La libertad es un derecho fundamental.",
        "La confianza es la base de toda relación.",
        "La lealtad es una promesa sincera.",
        "La ética guía nuestras acciones.",
        "La libertad es un derecho sagrado.",
        "La perseverancia conduce al éxito.",
        "La generosidad abre puertas.",
        "El respeto mutuo es esencial.",
        "La gratitud nos llena de alegría.",
        "La amistad es un tesoro inestimable.",
        "La comprensión construye puentes.",
        "La tolerancia fomenta la convivencia.",
        "La confianza es fundamental en todas las relaciones.",
        "La humildad es una virtud valiosa.",
        "Siembra buenas acciones y cosecharás buenos resultados.",
        "La vida es un viaje, no un destino.",
        "La simplicidad es la última sofisticación.",
        "La curiosidad conduce al conocimiento.",
        "El cambio es la única constante en la vida.",
        "La imaginación es el principio de la creación.",
        "La diversidad nos enriquece.",
        "La verdad siempre prevalece.",
        "La naturaleza es nuestro hogar.",
        "La felicidad viene de dentro.",
        "La empatía es fundamental para entender a los demás.",
        "La libertad es un derecho humano fundamental.",
        "Aprende de tus errores y sigue adelante.",
        "El amor todo lo puede.",
        "La perseverancia es la madre del éxito.",
        "El conocimiento es poder.",
        "La tecnología está cambiando el mundo.",
        "El trabajo en equipo es esencial.",
        "Cada día es una nueva oportunidad.",
        "La pasión te impulsa a alcanzar tus metas.",
        "La gratitud transforma la vida.",
        "La amabilidad es contagiosa.",
        "El arte es una forma de expresión.",
        "La justicia es un pilar de la sociedad.",
        "La salud es riqueza.",
        "La honestidad es la mejor política.",
        "El amor es lo que realmente importa.",
        "La perseverancia supera el talento.",
        "El cambio es una oportunidad para crecer.",
        "La música alimenta el alma.",
        "La educación es un camino hacia el éxito.",
        "El silencio a veces es la mejor respuesta.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con el tiempo.",
        "La libertad es un derecho sagrado.",
        "El éxito es un viaje, no un destino.",
        "El aprendizaje es un proceso continuo.",
        "El respeto es la base de todas las relaciones.",
        "La amistad verdadera perdura.",
        "La valentía supera el miedo.",
        "La gratitud cambia la perspectiva.",
        "El amor trae alegría a la vida.",
        "La risa alivia el estrés.",
        "La belleza está en todas partes.",
        "La curiosidad despierta la mente.",
        "La pasión impulsa la creatividad.",
        "La paciencia es una fuente de fortaleza.",
        "La creatividad no tiene límites.",
        "La comprensión genera armonía.",
        "La sinceridad construye relaciones sólidas.",
        "La amistad es un lazo indestructible.",
        "La generosidad es una virtud admirable.",
        "La honestidad es un acto de valentía.",
        "El amor es un regalo preciado.",
        "La sonrisa es un gesto poderoso.",
        "La educación es el camino hacia el progreso.",
        "La compasión alivia el sufrimiento.",
        "La paciencia es una virtud valiosa.",
        "La familia es un refugio seguro.",
        "La confianza se gana con acciones.",
        "La lealtad es un tesoro.",
        "La ética guía nuestras decisiones.",
        "La libertad es un derecho fundamental.",
        "La confianza es la base de toda relación.",
        "La lealtad es una promesa sincera.",
        "La ética guía nuestras acciones.",
        "La libertad es un derecho sagrado.",
        "La perseverancia conduce al éxito.",
        "La generosidad abre puertas.",
        "El respeto mutuo es esencial.",
        "La gratitud nos llena de alegría.",
        "La amistad es un tesoro inestim"
    ])
}